# ArgoCD Config Management Plugin for Terraform
apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-cmp-plugin
  namespace: argocd
data:
  terraform-cmp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: terraform-cmp
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args:
          - |
            echo "🔧 Initializing Terraform GitOps with ArgoCD..."
            
            # Install required tools
            apk add --no-cache python3 py3-pip jq curl
            pip3 install pyyaml boto3 jinja2
            
            # Download OPA
            curl -L -o opa https://openpolicyagent.org/downloads/v0.59.0/opa_linux_amd64_static
            chmod +x opa && mv opa /usr/local/bin/
            
            # Setup Git authentication
            git config --global url."https://oauth2:${ARGOCD_GIT_TOKEN}@github.com".insteadOf "https://github.com"
            
            echo "✅ Initialization complete"
      
      generate:
        command: [sh, -c]
        args:
          - |
            echo "🚀 Generating Terraform manifests..."
            
            # Run deployment discovery
            python3 scripts/terraform-deployment-orchestrator.py discover \
              --changed-files "$(git diff --name-only HEAD~1 HEAD | grep -E '\.(tfvars|json|yaml)$' | tr '\n' ' ')" \
              --output-summary deployments.json \
              --argocd-mode
            
            # Generate Kubernetes Job manifests for each deployment
            python3 scripts/argocd-terraform-generator.py \
              --deployments-json deployments.json \
              --output-dir ./manifests
            
            echo "✅ Generated $(ls manifests/*.yaml | wc -l) Terraform job manifests"
      
      discover:
        fileName: "deployments.json"
---
# ArgoCD Repository Configuration
apiVersion: v1
kind: Secret
metadata:
  name: terraform-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/Terraform-centilazed-pipline/dev-deployment.git
  password: ${GITHUB_TOKEN}
  username: oauth2